name       : libe-book
version    : 0.1.2
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/libebook/libe-book-0.1.2/libe-book-0.1.2.tar.xz : 7f894b1538b71c6cd96c976069c4dadb38b623612f0e35b2f6ee8a2c46bb88ec
license    : MPL-2.0
component  : programming
summary    : Library and tools for reading and converting e-book formats
description: |
    libe-book is a library and a set of tools for reading and converting various reflowable e-book formats.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(icu-i18n)
    - pkgconfig(librevenge-0.0)
    - gperf
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/fix-build-with-boost-1.59.patch
    %autogen --disable-werror
build      : |
    %make
install    : |
    %make_install
