name       : libe-book
version    : 0.1.3
release    : 13
source     :
    - https://download.sourceforge.net/project/libebook/libe-book-0.1.3/libe-book-0.1.3.tar.xz : 7e8d8ff34f27831aca3bc6f9cc532c2f90d2057c778963b884ff3d1e34dfe1f9
license    : MPL-2.0
component  : programming.library
summary    : Library and tools for reading and converting e-book formats
description: |
    libe-book is a library and a set of tools for reading and converting various reflowable e-book formats.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(icu-i18n)
    - pkgconfig(liblangtag)
    - pkgconfig(librevenge-0.0)
    - gperf
    - libboost-devel
setup      : |
    %patch -p0 < $pkgfiles/icu68.patch
    %configure --disable-werror
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
